name: release

on:
    push:
        branches: [ main ]

steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          fetch-depth: 0

    - name: Install .NET 7.0
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: '7.0.x'

    - name: Build, Tests, Cover, Pack and Publish (on push tag)
      shell: bash
      run: |
        dotnet pack ./NetObsBindings -o publish
        dotnet nuget push publish/*.nupkg -k ${{secrets.NUGET_TOKEN}} -s https://api.nuget.org/v3/index.json