name: release

on:
    push:
        branches: [ main ]
jobs:
    publish:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        env:
            DEPLOY_SECRET: ${{ secrets.NUGET_TOKEN }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Install .NET 7.0
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: '7.0.x'

            - name: Pack & Publish to nuget
              shell: bash
              run: |
                dotnet pack ./NetObsBindings -c release -o publish
                dotnet nuget push publish/*.nupkg -k ${{secrets.NUGET_TOKEN}} -s https://api.nuget.org/v3/index.json